============================= test session starts =============================
platform linux -- Python 3.9.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /Workspace/Users/mario89sergio@gmail.com/5.TesteUnitario
collected 2 items

unit_test.py::test_valores_validos PASSED                               [ 50%]
unit_test.py::test_valores_invalidos PASSED                             [100%]

============================== 2 passed in 0.47s ==============================

Resumo:
test_valores_validos: passou — Validação com dados consistentes.
test_valores_invalidos: passou — Validação de falhas esperadas em dados com problemas.

Todos os testes unitários foram executados com sucesso.
